#!/usr/bin/env python3
"""Keep the architecture docs honest.

The numbers in these documents are the part that rots: file counts, line
counts, test counts, and the crate list. Two structural documents in this
repo already drifted — CLAUDE.md claimed 11 crates and README.md claimed 10
when there were 13 — because nothing checked them.

So the numbers are generated rather than written. Each crate's
ARCHITECTURE.md carries a block delimited by the markers below; this script
regenerates it from the source tree and fails when what is committed differs.

    scripts/check_architecture_docs.py          # verify (CI)
    scripts/check_architecture_docs.py --fix    # regenerate

It also fails when a crate has no ARCHITECTURE.md at all, so adding a crate
means documenting it.

What it deliberately does NOT check is the prose. A reviewer's reasoning
cannot be verified mechanically, and pretending otherwise would just add
false confidence. This guards the facts; the argument is on you.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- begin:generated-metrics -->"
END = "<!-- end:generated-metrics -->"
TEST_ATTRS = re.compile(r"#\[(?:tokio::)?test\]")


def workspace_members() -> list[Path]:
    """Crates listed in the workspace, in declaration order."""
    manifest = (ROOT / "Cargo.toml").read_text()
    block = re.search(r"members\s*=\s*\[(.*?)\]", manifest, re.S)
    if not block:
        sys.exit("could not parse [workspace] members from Cargo.toml")
    names = re.findall(r'"([^"]+)"', block.group(1))
    return [ROOT / n for n in names]


def measure(crate: Path) -> dict:
    src = crate / "src"
    files = sorted(src.rglob("*.rs")) if src.is_dir() else []
    lines = 0
    tests = 0
    for f in files:
        text = f.read_text(errors="replace")
        lines += text.count("\n")
        tests += len(TEST_ATTRS.findall(text))
    # Integration tests live outside src/ but are part of the crate's coverage.
    for f in sorted((crate / "tests").rglob("*.rs")) if (crate / "tests").is_dir() else []:
        tests += len(TEST_ATTRS.findall(f.read_text(errors="replace")))

    manifest = (crate / "Cargo.toml").read_text()
    me = crate.name
    deps = sorted({
        d for d in re.findall(r"rustykrab-[a-z0-9-]+", manifest) if d != me
    })
    return {"files": len(files), "lines": lines, "tests": tests, "deps": deps}


def render(crate: Path, m: dict) -> str:
    deps = ", ".join(f"`{d.removeprefix('rustykrab-')}`" for d in m["deps"]) or "nothing"
    return (
        f"{BEGIN}\n"
        f"*{m['files']} files · {m['lines']:,} lines · {m['tests']} tests · "
        f"depends on {deps}.*\n"
        f"\n"
        f"<sub>Generated by `scripts/check_architecture_docs.py`. "
        f"Run it with `--fix` after changing this crate.</sub>\n"
        f"{END}"
    )


def apply(doc: Path, block: str) -> str:
    text = doc.read_text()
    if BEGIN in text and END in text:
        return re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END), block.replace("\\", "\\\\"), text, flags=re.S
        )
    # Insert after the title line so it reads as a subtitle.
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("# "):
            lines.insert(i + 1, "\n" + block)
            return "\n".join(lines)
    return block + "\n\n" + text


def main() -> int:
    fix = "--fix" in sys.argv
    stale: list[str] = []
    missing: list[str] = []

    for crate in workspace_members():
        doc = crate / "ARCHITECTURE.md"
        if not doc.is_file():
            missing.append(f"{crate.relative_to(ROOT)}/ARCHITECTURE.md")
            continue
        want = render(crate, measure(crate))
        updated = apply(doc, want)
        if updated != doc.read_text():
            if fix:
                doc.write_text(updated)
            else:
                stale.append(str(doc.relative_to(ROOT)))

    # The crate count appears in prose in several places; check rather than
    # rewrite, because the surrounding sentence is not ours to regenerate.
    count = len(workspace_members())
    wrong_counts = []
    for rel in ("CLAUDE.md", "README.md", "docs/architecture/README.md",
                "docs/architecture/00-system-overview.md"):
        f = ROOT / rel
        if not f.is_file():
            continue
        # Only the assertion form — "a workspace of N crates", "N crates
        # under crates/". Prose may legitimately cite a historical count
        # ("used to claim 11 crates"), and flagging that would train people
        # to ignore this check.
        pattern = r"(?:workspace (?:of|with) |^| )(\d+) crates(?= under| under\b|\.|,|:|$)"
        for claimed in re.findall(pattern, f.read_text(), re.M):
            if int(claimed) != count:
                wrong_counts.append(f"{rel}: says {claimed} crates, there are {count}")

    if missing:
        print("Crates without an ARCHITECTURE.md:", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
    if stale:
        print("Stale generated metrics (run with --fix):", file=sys.stderr)
        for s in stale:
            print(f"  {s}", file=sys.stderr)
    if wrong_counts:
        print("Crate count is wrong (edit the prose by hand):", file=sys.stderr)
        for w in wrong_counts:
            print(f"  {w}", file=sys.stderr)

    if missing or stale or wrong_counts:
        return 1
    print(f"architecture docs OK — {count} crates, all documented, metrics current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
