use openclaw_core::Error;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A single fact stored in associative memory.
///
/// Modeled on neuroscience findings: each memory is stored with
/// association tags that enable content-addressable retrieval.
/// Tags are generated by the agent at encoding time ("depth of
/// processing") and matched against conversation keywords at
/// retrieval time ("pattern completion").
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    /// Unique ID for this memory entry.
    pub id: Uuid,
    /// The conversation this memory belongs to.
    pub conversation_id: Uuid,
    /// The fact or knowledge to remember.
    pub fact: String,
    /// Association tags for content-addressable retrieval.
    /// The agent generates these at write time to capture
    /// the concepts that should trigger recall.
    pub tags: Vec<String>,
    /// When this memory was created.
    pub created_at: chrono::DateTime<chrono::Utc>,
    /// When this memory was last accessed (for decay).
    pub last_accessed: chrono::DateTime<chrono::Utc>,
    /// Access count (for spaced-repetition-style relevance).
    pub access_count: u32,
}

/// Persistent associative memory store backed by a sled tree.
///
/// Supports multiple entries per conversation. Retrieval is by
/// tag matching against the conversation's stored memories,
/// mimicking the brain's content-addressable recall.
#[derive(Clone)]
pub struct MemoryStore {
    tree: sled::Tree,
}

impl MemoryStore {
    pub(crate) fn new(tree: sled::Tree) -> Self {
        Self { tree }
    }

    /// Store a memory entry.
    pub fn save(&self, entry: &MemoryEntry) -> Result<(), Error> {
        let key = entry.id.as_bytes().to_vec();
        let bytes = serde_json::to_vec(entry)?;
        self.tree
            .insert(key, bytes)
            .map_err(|e| Error::Storage(e.to_string()))?;
        Ok(())
    }

    /// Retrieve a memory by its unique ID.
    pub fn get(&self, id: Uuid) -> Result<MemoryEntry, Error> {
        let bytes = self
            .tree
            .get(id.as_bytes())
            .map_err(|e| Error::Storage(e.to_string()))?
            .ok_or_else(|| Error::NotFound(format!("memory {id}")))?;
        let entry: MemoryEntry = serde_json::from_slice(&bytes)?;
        Ok(entry)
    }

    /// Find memories for a conversation whose tags match any of the
    /// given keywords. This is the associative retrieval mechanism:
    /// keywords from the user's message are matched against stored
    /// tags to surface relevant memories automatically.
    ///
    /// Updates `last_accessed` and `access_count` on matched entries
    /// (reconsolidation — retrieval strengthens the memory).
    pub fn recall(
        &self,
        conversation_id: Uuid,
        keywords: &[String],
    ) -> Result<Vec<MemoryEntry>, Error> {
        if keywords.is_empty() {
            return Ok(Vec::new());
        }
        let keywords_lower: Vec<String> = keywords.iter().map(|k| k.to_lowercase()).collect();
        let mut results = Vec::new();

        for item in self.tree.iter() {
            let (key, value) = item.map_err(|e| Error::Storage(e.to_string()))?;
            let mut entry: MemoryEntry = serde_json::from_slice(&value)?;

            if entry.conversation_id != conversation_id {
                continue;
            }

            let matches = entry.tags.iter().any(|tag| {
                let tag_lower = tag.to_lowercase();
                keywords_lower.iter().any(|kw| tag_lower.contains(kw) || kw.contains(&tag_lower))
            });

            if matches {
                // Reconsolidation: update access metadata.
                entry.last_accessed = chrono::Utc::now();
                entry.access_count += 1;
                let bytes = serde_json::to_vec(&entry)?;
                self.tree
                    .insert(key, bytes)
                    .map_err(|e| Error::Storage(e.to_string()))?;
                results.push(entry);
            }
        }

        // Most recently accessed first.
        results.sort_by(|a, b| b.last_accessed.cmp(&a.last_accessed));
        Ok(results)
    }

    /// List all memories for a conversation.
    pub fn list_for_conversation(
        &self,
        conversation_id: Uuid,
    ) -> Result<Vec<MemoryEntry>, Error> {
        let mut entries = Vec::new();
        for item in self.tree.iter() {
            let (_, value) = item.map_err(|e| Error::Storage(e.to_string()))?;
            let entry: MemoryEntry = serde_json::from_slice(&value)?;
            if entry.conversation_id == conversation_id {
                entries.push(entry);
            }
        }
        entries.sort_by(|a, b| b.created_at.cmp(&a.created_at));
        Ok(entries)
    }

    /// Delete a specific memory entry.
    pub fn delete(&self, id: Uuid) -> Result<(), Error> {
        self.tree
            .remove(id.as_bytes())
            .map_err(|e| Error::Storage(e.to_string()))?;
        Ok(())
    }

    /// Delete all memories for a conversation.
    pub fn delete_for_conversation(&self, conversation_id: Uuid) -> Result<u32, Error> {
        let entries = self.list_for_conversation(conversation_id)?;
        let count = entries.len() as u32;
        for entry in entries {
            self.tree
                .remove(entry.id.as_bytes())
                .map_err(|e| Error::Storage(e.to_string()))?;
        }
        Ok(count)
    }
}

/// Extract keywords from a text string for associative matching.
///
/// Simple tokenization + stopword removal. No LLM call needed.
/// Returns lowercase keywords that are 3+ chars long.
pub fn extract_keywords(text: &str) -> Vec<String> {
    const STOPWORDS: &[&str] = &[
        "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
        "have", "has", "had", "do", "does", "did", "will", "would", "could",
        "should", "may", "might", "shall", "can", "need", "dare", "ought",
        "used", "to", "of", "in", "for", "on", "with", "at", "by", "from",
        "as", "into", "through", "during", "before", "after", "above",
        "below", "between", "out", "off", "over", "under", "again",
        "further", "then", "once", "here", "there", "when", "where", "why",
        "how", "all", "both", "each", "few", "more", "most", "other",
        "some", "such", "no", "nor", "not", "only", "own", "same", "so",
        "than", "too", "very", "just", "don", "now", "and", "but", "or",
        "because", "if", "while", "that", "this", "these", "those", "what",
        "which", "who", "whom", "its", "it", "he", "she", "they", "them",
        "his", "her", "their", "our", "your", "my", "me", "we", "you",
        "about", "also", "get", "got", "like", "make", "made", "want",
        "let", "know", "think", "see", "come", "look", "use", "find",
        "give", "tell", "say", "said", "try", "ask", "work", "seem",
        "feel", "leave", "call", "keep", "put", "show", "take",
    ];

    text.split(|c: char| !c.is_alphanumeric() && c != '_' && c != '-')
        .map(|w| w.to_lowercase())
        .filter(|w| w.len() >= 3 && !STOPWORDS.contains(&w.as_str()))
        .collect::<Vec<_>>()
        .into_iter()
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect()
}
